name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Har 10 minute baad run ho ga

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Route3 Website
        run: |
          curl -s https://route3.com.pk/ > /dev/null
          echo "✅ Website pinged successfully at $(date)"
